[package]
name = "ripgzip"
version = "0.1.0"
authors = ["Sergei Fomin"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
byteorder = "1.4"
crc = "1.8"
log = "0.4"
stderrlog = "0.5"
structopt = "0.3"